apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbon-aware-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carbon-aware-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: carbon-aware-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carbon-aware-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: carbon-aware-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carbon-aware-scheduler-extension-apiserver-authentication-reader
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: carbon-aware-scheduler
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: carbon-aware-scheduler-secrets
  namespace: kube-system
type: Opaque
data:
  electricity-map-api-key: WU9VUl9FTEVDVFJJQ0lUWV9NQVBfQVBJX0tFWQ== # Base64 encoded "YOUR_ELECTRICITY_MAP_API_KEY"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-aware-scheduler-config
  namespace: kube-system
data:
  carbon-aware-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: carbon-aware-scheduler
        plugins:
          preFilter:
            enabled:
              - name: CarbonAwareScheduler
    leaderElection:
      leaderElect: false 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-aware-pricing-schedules
  namespace: kube-system
data:
  schedules.yaml: |
    # Time-of-use pricing schedule configuration
    # Format: day-of-week start-time end-time
    # day-of-week: 0-6 (Sunday=0)
    # time format: HH:MM in 24-hour format
    schedules:
      # Monday-Friday peak pricing periods (4pm-9pm)
      - dayOfWeek: "1-5"
        startTime: "16:00"
        endTime: "21:00"
      # Weekend peak pricing periods (1pm-7pm)
      - dayOfWeek: "0,6" 
        startTime: "13:00"
        endTime: "19:00"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: carbon-aware-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: carbon-aware-scheduler
      containers:
      - command:
        - /bin/kube-scheduler
        - --config=/etc/kubernetes/carbon-aware-scheduler/carbon-aware-scheduler-config.yaml
        image: docker.io/dmasselink/carbon-aware-scheduler:v20250223-
        imagePullPolicy: Always
        env:
        - name: ELECTRICITY_MAP_API_KEY
          valueFrom:
            secretKeyRef:
              name: carbon-aware-scheduler-secrets
              key: electricity-map-api-key
        - name: CARBON_INTENSITY_THRESHOLD
          value: "200.0"
        - name: MAX_SCHEDULING_DELAY
          value: "24h"
        - name: PRICING_ENABLED
          value: "false"
        - name: PRICING_PROVIDER
          value: "tou"
        - name: PRICING_BASE_RATE
          value: "0.10"
        - name: PRICING_PEAK_RATE
          value: "1.5"
        - name: PRICING_MAX_DELAY
          value: "6h"
        - name: PRICING_SCHEDULES_PATH
          value: "/etc/kubernetes/carbon-aware-scheduler/pricing-schedules.yaml"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: carbon-aware-kube-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts:
          - name: config-volume
            mountPath: /etc/kubernetes/carbon-aware-scheduler
          - name: pricing-schedules-volume
            mountPath: /etc/kubernetes/carbon-aware-scheduler/pricing-schedules.yaml
            subPath: schedules.yaml
      hostNetwork: false
      hostPID: false
      volumes:
        - name: config-volume
          configMap:
            name: carbon-aware-scheduler-config
        - name: pricing-schedules-volume
          configMap:
            name: carbon-aware-pricing-schedules
