apiVersion: batch/v1
kind: CronJob
metadata:
  name: carbon-aware-batch-job
spec:
  # Run at 2 AM every day - typically during off-peak hours
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # Higher thresholds for batch jobs since they're more flexible
            carbon-aware-scheduler.kubernetes.io/carbon-intensity-threshold: "400.0"
            price-aware-scheduler.kubernetes.io/price-threshold: "0.30"
            # Allow longer scheduling delays for batch jobs
            carbon-aware-scheduler.kubernetes.io/max-scheduling-delay: "12h"
        spec:
          schedulerName: carbon-aware-scheduler
          containers:
          - name: batch-processor
            image: batch-processor:1.0
            command:
            - /process-data.sh
            resources:
              requests:
                memory: "2Gi"
                cpu: "1000m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
            volumeMounts:
            - name: data
              mountPath: /data
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: batch-data-pvc
          restartPolicy: OnFailure
