apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-aware-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        carbon-aware-scheduler.kubernetes.io/carbon-intensity-threshold: "250.0"
        price-aware-scheduler.kubernetes.io/price-threshold: "0.18"
    spec:
      schedulerName: carbon-aware-scheduler
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
