apiVersion: v1
kind: Pod
metadata:
  name: opt-out-pod
  annotations:
    carbon-aware-scheduler.kubernetes.io/skip: "true"
    price-aware-scheduler.kubernetes.io/skip: "true"
spec:
  schedulerName: carbon-aware-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
